sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: lmtwpl12345
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: LTAI5t9xuoQTnxpFXzMCBNni
    access-key-secret: lrEuTIQ5l3r62zrM2M36OevrNBo6IT
    bucket-name: hy-tlias
